url: https://y7kim.github.io
baseurl: "" # the subpath of your site, e.g. /blog/

# Site settings
title: ShenzEd
email: your-email@domain.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Presenter names, titles and social links
presenters:
# - title: Pedagogical Possibilities in ICT
#   pic: louise_headshot
#   name: Louise Cullen
#   workshop-date: Dec 17, 2016
#   personalsite:
#   alt: image-alt
#   social:
#     - title: twitter
#       url: http://twitter.com/louise_cullen
#   modal-id: 1
#   description: In this session teachers will explore a variety of easy to use tech tools that will enhance pedagogical practices, and actively engage students in learning. Inspired and informed, participants will be motivated to implement fresh ideas for using Nearpod, Kahoot, Wizer Me, Plickers and Zaption in their own learning environments. Participants should bring a connected device.

# Past presenter names, titles and social links
past_presenters: 
- title: Pedagogical Possibilities in ICT
  pic: louise_headshot
  name: Louise Cullen
  workshop-date: March 2, 2017
  personalsite:
  alt: image-alt
  social:
    - title: twitter
      url: http://twitter.com/louise_cullen
  modal-id: 1
  description: In this session teachers will explore a variety of easy to use tech tools that will enhance pedagogical practices, and actively engage students in learning. Inspired and informed, participants will be motivated to implement fresh ideas for using Nearpod, Kahoot, Wizer Me, Plickers and Zaption in their own learning environments. Participants should bring a connected device.

- title: Doodling My Way Through the PYP
  pic: skinneard-headshot
  name: Stephanie Kinneard
  workshop-date: March 2, 2017
  personalsite:
  alt: image-alt
  social:
    - title: twitter
      url: http://twitter.com/misskinneard
  modal-id: 2
  description: There are many advantages to including drawings in my lessons and note-taking with students. My interest in doodling in class began in response to my students' needs. One year I found myself teaching a Grade 5 class with several special needs students who were unable to read. In order to not leave these students further behind, I began visual note-taking with the class so that students could make meaning through connecting images and pictures to the information that they were absorbing through listening. I quickly realized that these note-taking lessons were also highly benefiting not only these special needs learners, but my EAL and visual inclined learners as well. In this workshop I will provide tips for easy doodle integration while note-taking and give suggestions for ways that students can use drawing to demonstrate their understanding of material.

- title: Coding Across the Subjects
  pic: AWheeler-headshot
  name: Andrew Wheeler
  workshop-date: March 2, 2017
  personalsite: http://www.drew-wheeler.com
  alt: image-alt
  social:
    - title: twitter
      url: http://twitter.com/drew_wheels
    - title: linkedin
      url: https://www.linkedin.com/in/andwheeler
  modal-id: 3
  description: Are you interested in bringing coding into your classroom but just not sure where to start?<br><br> This introductory coding workshop is focused on helping you to see opportunities for its integration across various subject areas. As a mathematics teacher, I will show several examples of how I have used coding within my own classroom. In addition, I will provide some examples of possible student programming tasks that align with science, languages and art.<br><br>The level of prior knowledge required with programming is beginner to intermediate while the curricular examples will be aimed at grades 6 to 12. The coding examples will mainly use the Python programming language, with some examples using Scratch. It is encouraged that participants bring their laptops if possible, as time permitting, we will end the session by coding a basic math program.


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  # - title: twitter
  #   url: http://twitter.com/jekyllrb
  # - title: stack-overflow
  #   url: http://stackoverflow.com/questions/tagged/jekyll
  # - title: bitbucket 
  #   url: http://bitbucket.org/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: Shenzhen, CN

# Build settings
markdown: kramdown
permalink: pretty